services:
  postgres_nto:
    image: postgres:latest
    container_name: postgres_nto
    environment:
      POSTGRES_USER: indexzero
      POSTGRES_PASSWORD: gkl370WVUPMgLhK
      POSTGRES_DB: application_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5429:5432"
    volumes:
      - postgres_nto_data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  postgres_nto_data:
    driver: local
